### ISSUE TITLE
I cloned this to my PC and nothing happened???

### ISSUE THREAD

**Issue by BradF-99** [aXises/MrFortnite#2]
Steps to reproduce: 
1. Cloned repository
2. Tried to run

Expected outcome: Runs 
Actual outcome: Did not

pls help!!!

**Comment by aXises** [comment]
Stay tuned, fix coming in next major release.

**Comment by Assasindie** [comment]
I am also experiencing a similar problem as @BradF-99 .

**Comment by aXises** [comment]
@BradF-99 @Assasindie should be fixed now.
